hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:65432/postgres
hibernate.connection.username=postgres
hibernate.connection.password=password

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

hibernate.hbm2ddl.auto=update

hibernate.show_sql=false
hibernate.format_sql=true
hibernate.highlight_sql=true

hibernate.generate_statistics=false

hibernate.cache.use_second_level_cache=true
hibernate.cache.region.factory_class=org.hibernate.cache.jcache.internal.JCacheRegionFactory
hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
hibernate.cache.use_query_cache=true

hibernate.connection.pool_size=5

hibernate.jdbc.batch_size=50
hibernate.order_inserts=true
