plugins {
    id 'java'
    id 'application'
    id ("org.openjfx.javafxplugin").version("0.1.0")
    id 'org.liquibase.gradle' version '2.2.0'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

configurations {
    liquibaseRuntime
}


dependencies {
    implementation 'com.microsoft.sqlserver:mssql-jdbc:13.3.2.jre11-preview'
    implementation 'org.knowm.xchart:xchart:3.8.3'
    runtimeOnly 'com.microsoft.sqlserver:mssql-jdbc_auth:12.6.1.x64'

    liquibaseRuntime 'org.liquibase:liquibase-core:4.23.1'
    liquibaseRuntime 'info.picocli:picocli:4.7.6'
    liquibaseRuntime 'com.microsoft.sqlserver:mssql-jdbc:13.3.2.jre11-preview'
    liquibaseRuntime 'org.slf4j:slf4j-simple:2.0.17'

    implementation("org.hibernate.orm:hibernate-core:6.4.10.Final")
    implementation("org.hibernate.orm:hibernate-hikaricp:6.4.10.Final")
    implementation 'org.hibernate.orm:hibernate-jcache:6.4.4.Final'
    implementation 'org.ehcache:ehcache:3.10.8'    // Source: https://mvnrepository.com/artifact/org.slf4j/slf4j-reload4j
    implementation("org.slf4j:slf4j-reload4j:2.0.17")

    implementation("com.zaxxer:HikariCP:7.0.0")

    implementation("org.apache.logging.log4j:log4j-core:2.25.4")
    implementation("org.apache.logging.log4j:log4j-api:2.25.4")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application{
    mainClass = 'org.example.Application'
    applicationDefaultJvmArgs = ['--enable-native-access=ALL-UNNAMED']
}

liquibase {
    activities {
        main {
            changelogFile 'src/main/resources/db/changelog/db.changelog-master.xml'
            url 'jdbc:sqlserver://localhost:1433;databaseName=proiect_sem2;integratedSecurity=false;encrypt=true;trustServerCertificate=true;'
            username 'user'
            password 'parola'
            driver 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
        }
    }
}
