changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
url=jdbc:sqlserver://localhost:1433;databaseName=proiect_sem2;integratedSecurity=false;encrypt=true;trustServerCertificate=true;
username=user
password=parola
driver=com.microsoft.sqlserver.jdbc.SQLServerDriver