drop TABLE "Rentals"
drop TABLE "Invoices"
drop TABLE "Employees"
drop TABLE "MaintenanceRecords"
drop TABLE "Suppliers"
drop TABLE "PartsInventory"
drop TABLE "MaintenanceParts"
drop TABLE "Customers"
